/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_syntaxerror_ini_IniUtil */

#ifndef _Included_at_syntaxerror_ini_IniUtil
#define _Included_at_syntaxerror_ini_IniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_syntaxerror_ini_IniUtil
 * Method:    set_implicit_value0
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_at_syntaxerror_ini_IniUtil_set_1implicit_1value0
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     at_syntaxerror_ini_IniUtil
 * Method:    load_ini_path0
 * Signature: (Ljava/lang/String;Lat/syntaxerror/ini/IniFormat;Ljava/util/function/Consumer;)I
 */
JNIEXPORT jint JNICALL Java_at_syntaxerror_ini_IniUtil_load_1ini_1path0
  (JNIEnv *, jclass, jstring, jobject, jobject);

/*
 * Class:     at_syntaxerror_ini_IniUtil
 * Method:    enable_debug
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_at_syntaxerror_ini_IniUtil_enable_1debug
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
